"""
qrng.py
========
Quantum Random Number Generator (QRNG) using Qiskit.

This module is the "quantum layer" of the project. Instead of relying purely
on classical pseudo-random number generators (PRNGs) like Python's `random`
or even `os.urandom` (which is cryptographically secure but still classical),
this module generates randomness from a genuine quantum mechanical process:

    1. A qubit is initialised in state |0>.
    2. A Hadamard gate (H) is applied, putting it into an equal superposition
       of |0> and |1>  ->  (|0> + |1>) / sqrt(2)
    3. The qubit is measured. Quantum mechanics guarantees the outcome is
       fundamentally probabilistic (not just "hard to predict" like a PRNG,
       but truly undetermined until measured) and gives 0 or 1 with 50/50
       probability.

Run many qubits through this circuit in one shot and you get a string of
random bits, which we pack into random bytes.

On real quantum hardware this randomness is provably non-deterministic.
Here we run it on Qiskit's Aer simulator (a classical simulation of a
quantum computer) so the project works offline without needing an IBM
Quantum account -- but the SAME circuit could be pointed at real quantum
hardware by swapping the backend (see `run_on_real_hardware` notes below).
"""

from __future__ import annotations

import math
from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator


class QuantumRandomGenerator:
    """
    Generates random bytes using a quantum circuit (Hadamard + measurement)
    executed on Qiskit's Aer simulator.
    """

    def __init__(self, backend_name: str = "aer_simulator"):
        self.backend = AerSimulator()
        self.backend_name = backend_name

    def _build_circuit(self, num_qubits: int) -> QuantumCircuit:
        """
        Build a circuit with `num_qubits` qubits, each put into superposition
        via a Hadamard gate, then measured.

        Qiskit limits practical circuit width, so we cap and loop in the
        caller for large byte requests rather than building huge circuits.
        """
        qc = QuantumCircuit(num_qubits, num_qubits)
        qc.h(range(num_qubits))          # superposition on every qubit
        qc.measure(range(num_qubits), range(num_qubits))
        return qc

    def get_random_bits(self, num_bits: int) -> str:
        """
        Returns a string of '0'/'1' characters of length `num_bits`,
        generated by measuring qubits in superposition.
        """
        if num_bits <= 0:
            return ""

        max_qubits_per_run = 24  # keep simulator circuits small & fast
        bits = ""

        remaining = num_bits
        while remaining > 0:
            chunk = min(max_qubits_per_run, remaining)
            qc = self._build_circuit(chunk)

            # transpile is skipped here deliberately: Aer simulator can run
            # this simple circuit directly. shots=1 because we just need
            # ONE measurement outcome per qubit, like flipping a quantum coin.
            job = self.backend.run(qc, shots=1, memory=True)
            result = job.result()
            memory = result.get_memory(qc)  # e.g. ['101101...']
            bitstring = memory[0]

            bits += bitstring
            remaining -= chunk

        return bits[:num_bits]

    def get_random_bytes(self, num_bytes: int) -> bytes:
        """
        Returns `num_bytes` of random data generated from quantum
        measurements. Used as the source of entropy for AES key/salt
        material in crypto_engine.py.
        """
        num_bits = num_bytes * 8
        bitstring = self.get_random_bits(num_bits)

        byte_values = bytearray()
        for i in range(0, len(bitstring), 8):
            byte_chunk = bitstring[i:i + 8]
            byte_values.append(int(byte_chunk, 2))

        return bytes(byte_values)

    def get_random_int(self, max_value: int) -> int:
        """
        Returns a quantum-random integer in [0, max_value], using rejection
        sampling so the result is unbiased (avoids modulo bias).
        """
        if max_value <= 0:
            return 0

        num_bits = max_value.bit_length()
        while True:
            candidate = int(self.get_random_bits(num_bits), 2)
            if candidate <= max_value:
                return candidate


# -----------------------------------------------------------------------
# NOTE for viva / report: switching to REAL quantum hardware
# -----------------------------------------------------------------------
# To run this on actual IBM Quantum hardware instead of the simulator:
#
#   from qiskit_ibm_runtime import QiskitRuntimeService
#   service = QiskitRuntimeService(channel="ibm_quantum", token="<YOUR_TOKEN>")
#   backend = service.least_busy(operational=True, simulator=False)
#
# and pass `backend` into the SamplerV2 primitive instead of AerSimulator.
# This requires a free IBM Quantum account and has queue wait times, so the
# simulator is used by default for a responsive desktop app.
# -----------------------------------------------------------------------


if __name__ == "__main__":
    # Quick manual test: generate and display some quantum randomness
    qrng = QuantumRandomGenerator()
    print("8 random bits :", qrng.get_random_bits(8))
    print("16 random bytes (hex):", qrng.get_random_bytes(16).hex())
    print("Random int in [0,255]:", qrng.get_random_int(255))
